name: sistem_presensi
description: Sistem presensi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  google_fonts: ^4.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  firebase_auth: ^4.3.0
  intl: ^0.17.0
  table_calendar: ^3.0.8
  dropdown_button2: ^2.1.0
  camera: ^0.10.5
  path_provider: ^2.0.14
  path: ^1.8.2
  timelines: ^0.1.0
  localization: ^2.1.0
  firebase_storage: ^11.2.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  card_loading: ^0.3.0
  google_mlkit_face_detection: ^0.6.0
  image: ^4.0.17
  ffi: ^2.0.2
  tflite_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/models/
