// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyAuhdwgAombizL6WNdEPw8VvrTMBqre2o8',
  //   appId: '1:135690144903:web:96fd34d43081c0112c7c22',
  //   messagingSenderId: '135690144903',
  //   projectId: 'school-attendance-system-e683c',
  //   authDomain: 'school-attendance-system-e683c.firebaseapp.com',
  //   storageBucket: 'school-attendance-system-e683c.appspot.com',
  //   measurementId: 'G-P8LFKJ03C8',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGwxS7zzz91Pri9XioSJab3c3oLjanMKI',
    appId: '1:298000089490:android:91a2193edbc83d6dbf414b',
    messagingSenderId: '298000089490',
    projectId: 'sistem-presensi-28d61',
    storageBucket: 'sistem-presensi-28d61.appspot.com',
  );
}
